security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        refresh:
            pattern: ^/auth/token/refresh
            stateless: true
            refresh_jwt: true
            security: false
        login:
            pattern: ^/auth/login
            stateless: true
            security: false
        register:
            pattern: ^/auth/register
            stateless: true
            security: false
        main:
            stateless: true
            jwt: true
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/auth/(login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/me, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
